baseURL = "https://drhaemincho.netlify.com/"
languageCode = "en-us"
title = "Dr. Haemin Cho"

# theme = "personal-web"

# [params.intro]
#   main = "Hi, I'm Dr. Haemin Cho :wave:"
#   sub = "I'm a doctor of chinese medicine"

# [params.social]
#   github = "https://github.com/drhaemincho"

theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Service"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Portfolio"
    URL = "portfolio"
    weight = 4

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

    [[menu.nav]]
    name = "Pricing"
    URL = "pricing"
    weight = 6

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8